// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLog = `-- name: CountAuditLog :one
SELECT count(*) FROM audit_log
WHERE ($1::audit_action IS NULL OR action = $1)
  AND ($2::audit_target_type IS NULL OR target_type = $2)
  AND ($3::bigint IS NULL OR target_id = $3)
  AND ($4::bigint IS NULL OR actor_id = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
`

type CountAuditLogParams struct {
	Action      NullAuditAction     `json:"action"`
	TargetType  NullAuditTargetType `json:"target_type"`
	TargetID    pgtype.Int8         `json:"target_id"`
	ActorID     pgtype.Int8         `json:"actor_id"`
	CreatedFrom pgtype.Timestamptz  `json:"created_from"`
	CreatedTo   pgtype.Timestamptz  `json:"created_to"`
}

func (q *Queries) CountAuditLog(ctx context.Context, arg CountAuditLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLog,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.ActorID,
		arg.CreatedFrom,
		arg.CreatedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, created_at, actor_id, actor_name, action, target_type, target_id, target_label, changes, context FROM audit_log
WHERE ($1::audit_action IS NULL OR action = $1)
  AND ($2::audit_target_type IS NULL OR target_type = $2)
  AND ($3::bigint IS NULL OR target_id = $3)
  AND ($4::bigint IS NULL OR actor_id = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
ORDER BY created_at DESC, id DESC
LIMIT $8 OFFSET $7
`

type ListAuditLogParams struct {
	Action      NullAuditAction     `json:"action"`
	TargetType  NullAuditTargetType `json:"target_type"`
	TargetID    pgtype.Int8         `json:"target_id"`
	ActorID     pgtype.Int8         `json:"actor_id"`
	CreatedFrom pgtype.Timestamptz  `json:"created_from"`
	CreatedTo   pgtype.Timestamptz  `json:"created_to"`
	OffsetVal   int32               `json:"offset_val"`
	LimitVal    int32               `json:"limit_val"`
}

// Newest first. The id tiebreaker keeps pagination stable: a bulk add writes a whole batch of rows
// under one created_at.
func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.ActorID,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.TargetLabel,
			&i.Changes,
			&i.Context,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogActors = `-- name: ListAuditLogActors :many
SELECT DISTINCT ON (actor_id) actor_id::bigint AS id, actor_name AS name
FROM audit_log
WHERE actor_id IS NOT NULL
ORDER BY actor_id, id DESC
`

type ListAuditLogActorsRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// Everyone who has ever made a recorded change, for the actor filter. Mirrors ListItemRequestUsers.
//
// Deleted users drop out: their actor_id is nulled, so there is no id left to filter by. Their
// entries stay in the log and still show the name they acted under - they just cannot be singled out
// by this filter any more.
//
// The name is the most recent snapshot rather than the live one, which is why this reads off
// audit_log instead of joining users: it costs no join, and it is the name that matches what the
// entries themselves say.
func (q *Queries) ListAuditLogActors(ctx context.Context) ([]ListAuditLogActorsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogActors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogActorsRow
	for rows.Next() {
		var i ListAuditLogActorsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeAuditEntries = `-- name: WriteAuditEntries :exec
INSERT INTO audit_log (actor_id, actor_name, action, target_type, target_id, target_label, changes, context)
SELECT
  $1::bigint,
  COALESCE((SELECT full_name FROM users WHERE id = $1::bigint), ''),
  $2::audit_action,
  $3::audit_target_type,
  entry.target_id,
  entry.target_label,
  entry.changes,
  entry.context
FROM ROWS FROM (
  unnest($4::bigint[]),
  unnest($5::text[]),
  unnest($6::jsonb[]),
  unnest($7::jsonb[])
) AS entry(target_id, target_label, changes, context)
`

type WriteAuditEntriesParams struct {
	ActorID      pgtype.Int8       `json:"actor_id"`
	Action       AuditAction       `json:"action"`
	TargetType   AuditTargetType   `json:"target_type"`
	TargetIds    []int64           `json:"target_ids"`
	TargetLabels []string          `json:"target_labels"`
	Changes      []json.RawMessage `json:"changes"`
	Contexts     []json.RawMessage `json:"contexts"`
}

// One action against several targets in a single statement, the way CreateNotifications inserts one
// row per recipient. Used by CreateItem, which makes up to 100 items in a call, and by
// ApproveItemRequest, which supersedes every other pending request for the item at once.
func (q *Queries) WriteAuditEntries(ctx context.Context, arg WriteAuditEntriesParams) error {
	_, err := q.db.Exec(ctx, writeAuditEntries,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetIds,
		arg.TargetLabels,
		arg.Changes,
		arg.Contexts,
	)
	return err
}

const writeAuditEntry = `-- name: WriteAuditEntry :exec
INSERT INTO audit_log (actor_id, actor_name, action, target_type, target_id, target_label, changes, context)
VALUES (
  $1::bigint,
  COALESCE((SELECT full_name FROM users WHERE id = $1::bigint), ''),
  $2::audit_action,
  $3::audit_target_type,
  $4::bigint,
  $5::text,
  $6::jsonb,
  $7::jsonb
)
`

type WriteAuditEntryParams struct {
	ActorID     pgtype.Int8     `json:"actor_id"`
	Action      AuditAction     `json:"action"`
	TargetType  AuditTargetType `json:"target_type"`
	TargetID    int64           `json:"target_id"`
	TargetLabel string          `json:"target_label"`
	Changes     json.RawMessage `json:"changes"`
	Context     json.RawMessage `json:"context"`
}

// The actor's display name is snapshotted here rather than looked up first, so recording a change
// costs no extra round trip. An empty actor_name means there was no user behind the change at all -
// the seeder, or a future background job - which the client words however it likes. That is distinct
// from a null actor_id with a name, which is a user who has since been deleted.
func (q *Queries) WriteAuditEntry(ctx context.Context, arg WriteAuditEntryParams) error {
	_, err := q.db.Exec(ctx, writeAuditEntry,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.TargetLabel,
		arg.Changes,
		arg.Context,
	)
	return err
}
