// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_requests.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveItemRequest = `-- name: ApproveItemRequest :one
UPDATE item_requests 
SET status = 'approved' 
WHERE user_id = $1 AND item_id = $2 AND status = 'requested' 
RETURNING user_id, item_id, created_at, status, reason
`

type ApproveItemRequestParams struct {
	UserID int64 `json:"user_id"`
	ItemID int64 `json:"item_id"`
}

func (q *Queries) ApproveItemRequest(ctx context.Context, arg ApproveItemRequestParams) (ItemRequest, error) {
	row := q.db.QueryRow(ctx, approveItemRequest, arg.UserID, arg.ItemID)
	var i ItemRequest
	err := row.Scan(
		&i.UserID,
		&i.ItemID,
		&i.CreatedAt,
		&i.Status,
		&i.Reason,
	)
	return i, err
}

const checkItemsForRequests = `-- name: CheckItemsForRequests :many
SELECT user_id, item_id, created_at, status, reason FROM item_requests 
WHERE item_id = ANY($1::bigint[])
`

func (q *Queries) CheckItemsForRequests(ctx context.Context, itemIds []int64) ([]ItemRequest, error) {
	rows, err := q.db.Query(ctx, checkItemsForRequests, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemRequest
	for rows.Next() {
		var i ItemRequest
		if err := rows.Scan(
			&i.UserID,
			&i.ItemID,
			&i.CreatedAt,
			&i.Status,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countItemRequests = `-- name: CountItemRequests :one
SELECT count(*) FROM item_requests
WHERE ($1::request_status IS NULL OR status = $1)
  AND ($2::bigint IS NULL OR user_id = $2)
`

type CountItemRequestsParams struct {
	Status NullRequestStatus `json:"status"`
	UserID pgtype.Int8       `json:"user_id"`
}

func (q *Queries) CountItemRequests(ctx context.Context, arg CountItemRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countItemRequests, arg.Status, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItemRequest = `-- name: CreateItemRequest :one
INSERT INTO item_requests(user_id, item_id, status, reason) 
VALUES ($1, $2, $3, $4) 
RETURNING user_id, item_id, created_at, status, reason
`

type CreateItemRequestParams struct {
	UserID int64         `json:"user_id"`
	ItemID int64         `json:"item_id"`
	Status RequestStatus `json:"status"`
	Reason string        `json:"reason"`
}

func (q *Queries) CreateItemRequest(ctx context.Context, arg CreateItemRequestParams) (ItemRequest, error) {
	row := q.db.QueryRow(ctx, createItemRequest,
		arg.UserID,
		arg.ItemID,
		arg.Status,
		arg.Reason,
	)
	var i ItemRequest
	err := row.Scan(
		&i.UserID,
		&i.ItemID,
		&i.CreatedAt,
		&i.Status,
		&i.Reason,
	)
	return i, err
}

const deleteItemRequest = `-- name: DeleteItemRequest :execrows
DELETE FROM item_requests WHERE user_id = $1 AND item_id = $2
`

type DeleteItemRequestParams struct {
	UserID int64 `json:"user_id"`
	ItemID int64 `json:"item_id"`
}

func (q *Queries) DeleteItemRequest(ctx context.Context, arg DeleteItemRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItemRequest, arg.UserID, arg.ItemID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNonApprovedItemRequests = `-- name: DeleteNonApprovedItemRequests :execrows
DELETE FROM item_requests WHERE item_id = $1 AND status = 'requested'
`

func (q *Queries) DeleteNonApprovedItemRequests(ctx context.Context, itemID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNonApprovedItemRequests, itemID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getItemRequest = `-- name: GetItemRequest :one
SELECT user_id, item_id, created_at, status, reason FROM item_requests 
WHERE user_id = $1 AND item_id = $2
`

type GetItemRequestParams struct {
	UserID int64 `json:"user_id"`
	ItemID int64 `json:"item_id"`
}

func (q *Queries) GetItemRequest(ctx context.Context, arg GetItemRequestParams) (ItemRequest, error) {
	row := q.db.QueryRow(ctx, getItemRequest, arg.UserID, arg.ItemID)
	var i ItemRequest
	err := row.Scan(
		&i.UserID,
		&i.ItemID,
		&i.CreatedAt,
		&i.Status,
		&i.Reason,
	)
	return i, err
}

const listItemRequests = `-- name: ListItemRequests :many
SELECT user_id, item_id, created_at, status, reason FROM item_requests
WHERE ($1::request_status IS NULL OR status = $1)
  AND ($2::bigint IS NULL OR user_id = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListItemRequestsParams struct {
	Status    NullRequestStatus `json:"status"`
	UserID    pgtype.Int8       `json:"user_id"`
	OffsetVal int32             `json:"offset_val"`
	LimitVal  int32             `json:"limit_val"`
}

func (q *Queries) ListItemRequests(ctx context.Context, arg ListItemRequestsParams) ([]ItemRequest, error) {
	rows, err := q.db.Query(ctx, listItemRequests,
		arg.Status,
		arg.UserID,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemRequest
	for rows.Next() {
		var i ItemRequest
		if err := rows.Scan(
			&i.UserID,
			&i.ItemID,
			&i.CreatedAt,
			&i.Status,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
