// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_type.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const addItemTypeProperty = `-- name: AddItemTypeProperty :one
WITH locked_type AS (
  SELECT id FROM item_types WHERE id = $1 FOR UPDATE
), next_position AS (
  SELECT COALESCE(max(position), -1) + 1 AS position
  FROM item_type_properties
  WHERE type_id = $1
)
INSERT INTO item_type_properties (type_id, property_id, default_value, visibility, position)
SELECT $1, $2, $3, $4, next_position.position
FROM locked_type CROSS JOIN next_position
RETURNING type_id, property_id, default_value, visibility, position
`

type AddItemTypePropertyParams struct {
	TypeID       int64              `json:"type_id"`
	PropertyID   int64              `json:"property_id"`
	DefaultValue *json.RawMessage   `json:"default_value"`
	Visibility   PropertyVisibility `json:"visibility"`
}

func (q *Queries) AddItemTypeProperty(ctx context.Context, arg AddItemTypePropertyParams) (ItemTypeProperty, error) {
	row := q.db.QueryRow(ctx, addItemTypeProperty,
		arg.TypeID,
		arg.PropertyID,
		arg.DefaultValue,
		arg.Visibility,
	)
	var i ItemTypeProperty
	err := row.Scan(
		&i.TypeID,
		&i.PropertyID,
		&i.DefaultValue,
		&i.Visibility,
		&i.Position,
	)
	return i, err
}

const countItemTypes = `-- name: CountItemTypes :one
SELECT count(*) FROM item_types
WHERE name ILIKE '%' || escape_like_pattern($1) || '%'
`

func (q *Queries) CountItemTypes(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countItemTypes, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItemType = `-- name: CreateItemType :one
INSERT INTO item_types (name, description, derived_name_format, expiring_soon_days) VALUES ($1, $2, $3, $4) RETURNING id, name, description, derived_name_format, expiring_soon_days
`

type CreateItemTypeParams struct {
	Name              string      `json:"name"`
	Description       pgtype.Text `json:"description"`
	DerivedNameFormat pgtype.Text `json:"derived_name_format"`
	ExpiringSoonDays  pgtype.Int2 `json:"expiring_soon_days"`
}

func (q *Queries) CreateItemType(ctx context.Context, arg CreateItemTypeParams) (ItemType, error) {
	row := q.db.QueryRow(ctx, createItemType,
		arg.Name,
		arg.Description,
		arg.DerivedNameFormat,
		arg.ExpiringSoonDays,
	)
	var i ItemType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DerivedNameFormat,
		&i.ExpiringSoonDays,
	)
	return i, err
}

const deleteItemType = `-- name: DeleteItemType :execrows
DELETE FROM item_types WHERE id = $1
`

func (q *Queries) DeleteItemType(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItemType, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllItemTypes = `-- name: GetAllItemTypes :many
SELECT id, name, description, derived_name_format, expiring_soon_days FROM item_types
`

func (q *Queries) GetAllItemTypes(ctx context.Context) ([]ItemType, error) {
	rows, err := q.db.Query(ctx, getAllItemTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemType
	for rows.Next() {
		var i ItemType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DerivedNameFormat,
			&i.ExpiringSoonDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemTypeByID = `-- name: GetItemTypeByID :one
SELECT id, name, description, derived_name_format, expiring_soon_days FROM item_types
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetItemTypeByID(ctx context.Context, id int64) (ItemType, error) {
	row := q.db.QueryRow(ctx, getItemTypeByID, id)
	var i ItemType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DerivedNameFormat,
		&i.ExpiringSoonDays,
	)
	return i, err
}

const getItemTypeProperties = `-- name: GetItemTypeProperties :many
SELECT type_id, property_id, default_value, visibility, position FROM item_type_properties
WHERE type_id = ANY($1::bigint[])
ORDER BY type_id, position
`

func (q *Queries) GetItemTypeProperties(ctx context.Context, typeIds []int64) ([]ItemTypeProperty, error) {
	rows, err := q.db.Query(ctx, getItemTypeProperties, typeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemTypeProperty
	for rows.Next() {
		var i ItemTypeProperty
		if err := rows.Scan(
			&i.TypeID,
			&i.PropertyID,
			&i.DefaultValue,
			&i.Visibility,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemTypesByItemIDs = `-- name: GetItemTypesByItemIDs :many
SELECT item_types.id, item_types.name, item_types.description, item_types.derived_name_format, item_types.expiring_soon_days, items.id as item_id FROM item_types
JOIN items ON items.type_id = item_types.id
WHERE items.id = ANY($1::bigint[])
`

type GetItemTypesByItemIDsRow struct {
	ItemType ItemType `json:"item_type"`
	ItemID   int64    `json:"item_id"`
}

func (q *Queries) GetItemTypesByItemIDs(ctx context.Context, itemIds []int64) ([]GetItemTypesByItemIDsRow, error) {
	rows, err := q.db.Query(ctx, getItemTypesByItemIDs, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemTypesByItemIDsRow
	for rows.Next() {
		var i GetItemTypesByItemIDsRow
		if err := rows.Scan(
			&i.ItemType.ID,
			&i.ItemType.Name,
			&i.ItemType.Description,
			&i.ItemType.DerivedNameFormat,
			&i.ItemType.ExpiringSoonDays,
			&i.ItemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemTypeOptions = `-- name: ListItemTypeOptions :many
SELECT id, name FROM item_types
ORDER BY name
`

type ListItemTypeOptionsRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListItemTypeOptions(ctx context.Context) ([]ListItemTypeOptionsRow, error) {
	rows, err := q.db.Query(ctx, listItemTypeOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemTypeOptionsRow
	for rows.Next() {
		var i ListItemTypeOptionsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemTypes = `-- name: ListItemTypes :many
SELECT id, name, description, derived_name_format, expiring_soon_days FROM item_types
WHERE name ILIKE '%' || escape_like_pattern($1) || '%'
ORDER BY id
LIMIT $3 OFFSET $2
`

type ListItemTypesParams struct {
	Search    string `json:"search"`
	OffsetVal int32  `json:"offset_val"`
	LimitVal  int32  `json:"limit_val"`
}

func (q *Queries) ListItemTypes(ctx context.Context, arg ListItemTypesParams) ([]ItemType, error) {
	rows, err := q.db.Query(ctx, listItemTypes, arg.Search, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemType
	for rows.Next() {
		var i ItemType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DerivedNameFormat,
			&i.ExpiringSoonDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockItemType = `-- name: LockItemType :one
SELECT id, name, description, derived_name_format FROM item_types
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockItemType(ctx context.Context, id int64) (ItemType, error) {
	row := q.db.QueryRow(ctx, lockItemType, id)
	var i ItemType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DerivedNameFormat,
	)
	return i, err
}

const offsetItemTypePropertyPositions = `-- name: OffsetItemTypePropertyPositions :exec
UPDATE item_type_properties AS target
SET position = target.position + (
  SELECT COALESCE(max(source.position), -1) + 1
  FROM item_type_properties AS source
  WHERE source.type_id = target.type_id
)
WHERE target.type_id = $1
`

func (q *Queries) OffsetItemTypePropertyPositions(ctx context.Context, typeID int64) error {
	_, err := q.db.Exec(ctx, offsetItemTypePropertyPositions, typeID)
	return err
}

const removeItemTypeProperty = `-- name: RemoveItemTypeProperty :execrows
DELETE FROM item_type_properties WHERE type_id = $1 AND property_id = $2
`

type RemoveItemTypePropertyParams struct {
	TypeID     int64 `json:"type_id"`
	PropertyID int64 `json:"property_id"`
}

func (q *Queries) RemoveItemTypeProperty(ctx context.Context, arg RemoveItemTypePropertyParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeItemTypeProperty, arg.TypeID, arg.PropertyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setItemTypePropertyPosition = `-- name: SetItemTypePropertyPosition :execrows
UPDATE item_type_properties
SET position = $3
WHERE type_id = $1 AND property_id = $2
`

type SetItemTypePropertyPositionParams struct {
	TypeID     int64 `json:"type_id"`
	PropertyID int64 `json:"property_id"`
	Position   int32 `json:"position"`
}

func (q *Queries) SetItemTypePropertyPosition(ctx context.Context, arg SetItemTypePropertyPositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setItemTypePropertyPosition, arg.TypeID, arg.PropertyID, arg.Position)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateItemTypeProperty_DefaultValue = `-- name: UpdateItemTypeProperty_DefaultValue :one
UPDATE item_type_properties SET default_value = $3 WHERE type_id = $1 AND property_id = $2 RETURNING type_id, property_id, default_value, visibility, position
`

type UpdateItemTypeProperty_DefaultValueParams struct {
	TypeID       int64            `json:"type_id"`
	PropertyID   int64            `json:"property_id"`
	DefaultValue *json.RawMessage `json:"default_value"`
}

func (q *Queries) UpdateItemTypeProperty_DefaultValue(ctx context.Context, arg UpdateItemTypeProperty_DefaultValueParams) (ItemTypeProperty, error) {
	row := q.db.QueryRow(ctx, updateItemTypeProperty_DefaultValue, arg.TypeID, arg.PropertyID, arg.DefaultValue)
	var i ItemTypeProperty
	err := row.Scan(
		&i.TypeID,
		&i.PropertyID,
		&i.DefaultValue,
		&i.Visibility,
		&i.Position,
	)
	return i, err
}

const updateItemTypeProperty_Visibility = `-- name: UpdateItemTypeProperty_Visibility :one
UPDATE item_type_properties SET visibility = $3 WHERE type_id = $1 AND property_id = $2 RETURNING type_id, property_id, default_value, visibility, position
`

type UpdateItemTypeProperty_VisibilityParams struct {
	TypeID     int64              `json:"type_id"`
	PropertyID int64              `json:"property_id"`
	Visibility PropertyVisibility `json:"visibility"`
}

func (q *Queries) UpdateItemTypeProperty_Visibility(ctx context.Context, arg UpdateItemTypeProperty_VisibilityParams) (ItemTypeProperty, error) {
	row := q.db.QueryRow(ctx, updateItemTypeProperty_Visibility, arg.TypeID, arg.PropertyID, arg.Visibility)
	var i ItemTypeProperty
	err := row.Scan(
		&i.TypeID,
		&i.PropertyID,
		&i.DefaultValue,
		&i.Visibility,
		&i.Position,
	)
	return i, err
}

const updateItemType_DerivedNameFormat = `-- name: UpdateItemType_DerivedNameFormat :one
UPDATE item_types SET derived_name_format = $2 WHERE id = $1 RETURNING id, name, description, derived_name_format, expiring_soon_days
`

type UpdateItemType_DerivedNameFormatParams struct {
	ID                int64       `json:"id"`
	DerivedNameFormat pgtype.Text `json:"derived_name_format"`
}

func (q *Queries) UpdateItemType_DerivedNameFormat(ctx context.Context, arg UpdateItemType_DerivedNameFormatParams) (ItemType, error) {
	row := q.db.QueryRow(ctx, updateItemType_DerivedNameFormat, arg.ID, arg.DerivedNameFormat)
	var i ItemType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DerivedNameFormat,
		&i.ExpiringSoonDays,
	)
	return i, err
}

const updateItemType_Description = `-- name: UpdateItemType_Description :one
UPDATE item_types SET description = $2 WHERE id = $1 RETURNING id, name, description, derived_name_format, expiring_soon_days
`

type UpdateItemType_DescriptionParams struct {
	ID          int64       `json:"id"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateItemType_Description(ctx context.Context, arg UpdateItemType_DescriptionParams) (ItemType, error) {
	row := q.db.QueryRow(ctx, updateItemType_Description, arg.ID, arg.Description)
	var i ItemType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DerivedNameFormat,
		&i.ExpiringSoonDays,
	)
	return i, err
}

const updateItemType_ExpiringSoonDays = `-- name: UpdateItemType_ExpiringSoonDays :one
UPDATE item_types SET expiring_soon_days = $2 WHERE id = $1 RETURNING id, name, description, derived_name_format, expiring_soon_days
`

type UpdateItemType_ExpiringSoonDaysParams struct {
	ID               int64       `json:"id"`
	ExpiringSoonDays pgtype.Int2 `json:"expiring_soon_days"`
}

func (q *Queries) UpdateItemType_ExpiringSoonDays(ctx context.Context, arg UpdateItemType_ExpiringSoonDaysParams) (ItemType, error) {
	row := q.db.QueryRow(ctx, updateItemType_ExpiringSoonDays, arg.ID, arg.ExpiringSoonDays)
	var i ItemType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DerivedNameFormat,
		&i.ExpiringSoonDays,
	)
	return i, err
}

const updateItemType_Name = `-- name: UpdateItemType_Name :one
UPDATE item_types SET name = $2 WHERE id = $1 RETURNING id, name, description, derived_name_format, expiring_soon_days
`

type UpdateItemType_NameParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateItemType_Name(ctx context.Context, arg UpdateItemType_NameParams) (ItemType, error) {
	row := q.db.QueryRow(ctx, updateItemType_Name, arg.ID, arg.Name)
	var i ItemType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DerivedNameFormat,
		&i.ExpiringSoonDays,
	)
	return i, err
}
