// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addItemProperty = `-- name: AddItemProperty :one
INSERT INTO item_properties (item_id, property_id, property_value) VALUES ($1, $2, $3) RETURNING item_id, property_id, property_value
`

type AddItemPropertyParams struct {
	ItemID        int64  `json:"item_id"`
	PropertyID    int64  `json:"property_id"`
	PropertyValue string `json:"property_value"`
}

func (q *Queries) AddItemProperty(ctx context.Context, arg AddItemPropertyParams) (ItemProperty, error) {
	row := q.db.QueryRow(ctx, addItemProperty, arg.ItemID, arg.PropertyID, arg.PropertyValue)
	var i ItemProperty
	err := row.Scan(&i.ItemID, &i.PropertyID, &i.PropertyValue)
	return i, err
}

const addItemPropertyBulk = `-- name: AddItemPropertyBulk :many
INSERT INTO item_properties (item_id, property_id, property_value) 
SELECT 
    i.item_id, 
    $1, 
    $2
FROM unnest($3::bigint[]) AS i(item_id)
RETURNING item_id, property_id, property_value
`

type AddItemPropertyBulkParams struct {
	PropertyID    int64   `json:"property_id"`
	PropertyValue string  `json:"property_value"`
	ItemIds       []int64 `json:"item_ids"`
}

func (q *Queries) AddItemPropertyBulk(ctx context.Context, arg AddItemPropertyBulkParams) ([]ItemProperty, error) {
	rows, err := q.db.Query(ctx, addItemPropertyBulk, arg.PropertyID, arg.PropertyValue, arg.ItemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemProperty
	for rows.Next() {
		var i ItemProperty
		if err := rows.Scan(&i.ItemID, &i.PropertyID, &i.PropertyValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countItems = `-- name: CountItems :one
SELECT count(*) FROM items
WHERE ($1::bigint IS NULL OR type_id = $1)
  AND ($2::consumption_status[] IS NULL OR consumption = ANY($2::consumption_status[]))
  AND ($3::timestamptz IS NULL OR created_at >= $3)
  AND ($4::timestamptz IS NULL OR created_at <= $4)
`

type CountItemsParams struct {
	TypeID      pgtype.Int8         `json:"type_id"`
	Consumption []ConsumptionStatus `json:"consumption"`
	CreatedFrom pgtype.Timestamptz  `json:"created_from"`
	CreatedTo   pgtype.Timestamptz  `json:"created_to"`
}

func (q *Queries) CountItems(ctx context.Context, arg CountItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countItems,
		arg.TypeID,
		arg.Consumption,
		arg.CreatedFrom,
		arg.CreatedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItems = `-- name: CreateItems :many
INSERT INTO items (type_id) 
SELECT ($1) 
FROM generate_series(1, $2::integer)
RETURNING id, created_at, consumption, type_id
`

type CreateItemsParams struct {
	TypeID int64 `json:"type_id"`
	Amount int32 `json:"amount"`
}

func (q *Queries) CreateItems(ctx context.Context, arg CreateItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, createItems, arg.TypeID, arg.Amount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Consumption,
			&i.TypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteItem = `-- name: DeleteItem :execrows
DELETE FROM items WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, created_at, consumption, type_id FROM items
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetItemByID(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Consumption,
		&i.TypeID,
	)
	return i, err
}

const getItemProperties = `-- name: GetItemProperties :many
SELECT ip.item_id, ip.property_id, ip.property_value, itp.visibility, p.name AS property_name, it.derived_name_format FROM item_properties ip
JOIN items i ON ip.item_id = i.id
JOIN item_type_properties itp ON i.type_id = itp.type_id AND ip.property_id = itp.property_id 
JOIN item_types it ON i.type_id = it.id
JOIN properties p ON ip.property_id = p.id
WHERE ip.item_id = ANY($1::bigint[])
`

type GetItemPropertiesRow struct {
	ItemProperty      ItemProperty       `json:"item_property"`
	Visibility        PropertyVisibility `json:"visibility"`
	PropertyName      string             `json:"property_name"`
	DerivedNameFormat pgtype.Text        `json:"derived_name_format"`
}

func (q *Queries) GetItemProperties(ctx context.Context, itemIds []int64) ([]GetItemPropertiesRow, error) {
	rows, err := q.db.Query(ctx, getItemProperties, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemPropertiesRow
	for rows.Next() {
		var i GetItemPropertiesRow
		if err := rows.Scan(
			&i.ItemProperty.ItemID,
			&i.ItemProperty.PropertyID,
			&i.ItemProperty.PropertyValue,
			&i.Visibility,
			&i.PropertyName,
			&i.DerivedNameFormat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, created_at, consumption, type_id FROM items
WHERE ($1::bigint IS NULL OR type_id = $1)
  AND ($2::consumption_status[] IS NULL OR consumption = ANY($2::consumption_status[]))
  AND ($3::timestamptz IS NULL OR created_at >= $3)
  AND ($4::timestamptz IS NULL OR created_at <= $4)
ORDER BY
  CASE WHEN $5::bool THEN created_at END ASC,
  CASE WHEN $5::bool THEN id END ASC,
  CASE WHEN NOT $5::bool THEN created_at END DESC,
  CASE WHEN NOT $5::bool THEN id END DESC
LIMIT $7 OFFSET $6
`

type ListItemsParams struct {
	TypeID      pgtype.Int8         `json:"type_id"`
	Consumption []ConsumptionStatus `json:"consumption"`
	CreatedFrom pgtype.Timestamptz  `json:"created_from"`
	CreatedTo   pgtype.Timestamptz  `json:"created_to"`
	OrderAsc    bool                `json:"order_asc"`
	OffsetVal   int32               `json:"offset_val"`
	LimitVal    int32               `json:"limit_val"`
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems,
		arg.TypeID,
		arg.Consumption,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.OrderAsc,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Consumption,
			&i.TypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeItemProperty = `-- name: RemoveItemProperty :execrows
DELETE FROM item_properties WHERE item_id = $1 AND property_id = $2
`

type RemoveItemPropertyParams struct {
	ItemID     int64 `json:"item_id"`
	PropertyID int64 `json:"property_id"`
}

func (q *Queries) RemoveItemProperty(ctx context.Context, arg RemoveItemPropertyParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeItemProperty, arg.ItemID, arg.PropertyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateItemProperty = `-- name: UpdateItemProperty :one
UPDATE item_properties SET property_value = $3 WHERE item_id = $1 AND property_id = $2 RETURNING item_id, property_id, property_value
`

type UpdateItemPropertyParams struct {
	ItemID        int64  `json:"item_id"`
	PropertyID    int64  `json:"property_id"`
	PropertyValue string `json:"property_value"`
}

func (q *Queries) UpdateItemProperty(ctx context.Context, arg UpdateItemPropertyParams) (ItemProperty, error) {
	row := q.db.QueryRow(ctx, updateItemProperty, arg.ItemID, arg.PropertyID, arg.PropertyValue)
	var i ItemProperty
	err := row.Scan(&i.ItemID, &i.PropertyID, &i.PropertyValue)
	return i, err
}

const updateItem_Consumption = `-- name: UpdateItem_Consumption :one
UPDATE items SET consumption = $2 WHERE id = $1 RETURNING id, created_at, consumption, type_id
`

type UpdateItem_ConsumptionParams struct {
	ID          int64             `json:"id"`
	Consumption ConsumptionStatus `json:"consumption"`
}

func (q *Queries) UpdateItem_Consumption(ctx context.Context, arg UpdateItem_ConsumptionParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem_Consumption, arg.ID, arg.Consumption)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Consumption,
		&i.TypeID,
	)
	return i, err
}

const updateItem_Type = `-- name: UpdateItem_Type :one
UPDATE items SET type_id = $2 WHERE id = $1 RETURNING id, created_at, consumption, type_id
`

type UpdateItem_TypeParams struct {
	ID     int64 `json:"id"`
	TypeID int64 `json:"type_id"`
}

func (q *Queries) UpdateItem_Type(ctx context.Context, arg UpdateItem_TypeParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem_Type, arg.ID, arg.TypeID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Consumption,
		&i.TypeID,
	)
	return i, err
}
