// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkLocationCycle = `-- name: CheckLocationCycle :one
WITH RECURSIVE ancestors AS (
    SELECT id, parent_id FROM locations l WHERE l.id = cast($2 as bigint)
    UNION ALL
    SELECT l.id, l.parent_id
    FROM locations l
    JOIN ancestors a ON l.id = a.parent_id
)
SELECT EXISTS (
  SELECT 1 FROM ancestors a WHERE a.id = cast($1 as bigint)
) AS would_create_cycle
`

type CheckLocationCycleParams struct {
	LocationID int64 `json:"location_id"`
	ParentID   int64 `json:"parent_id"`
}

func (q *Queries) CheckLocationCycle(ctx context.Context, arg CheckLocationCycleParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkLocationCycle, arg.LocationID, arg.ParentID)
	var would_create_cycle bool
	err := row.Scan(&would_create_cycle)
	return would_create_cycle, err
}

const countLocations = `-- name: CountLocations :one
SELECT count(*) FROM locations
WHERE name ILIKE '%' || escape_like_pattern($1) || '%'
`

func (q *Queries) CountLocations(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countLocations, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (name, description, parent_id) 
VALUES ($1, $2, $3)
RETURNING id, name, description, parent_id
`

type CreateLocationParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ParentID    pgtype.Int8 `json:"parent_id"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation, arg.Name, arg.Description, arg.ParentID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :execrows
DELETE FROM locations WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLocation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, name, description, parent_id FROM locations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLocationByID(ctx context.Context, id int64) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
	)
	return i, err
}

const listLocationOptions = `-- name: ListLocationOptions :many
SELECT id, name, parent_id FROM locations
ORDER BY name
`

type ListLocationOptionsRow struct {
	ID       int64       `json:"id"`
	Name     string      `json:"name"`
	ParentID pgtype.Int8 `json:"parent_id"`
}

func (q *Queries) ListLocationOptions(ctx context.Context) ([]ListLocationOptionsRow, error) {
	rows, err := q.db.Query(ctx, listLocationOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationOptionsRow
	for rows.Next() {
		var i ListLocationOptionsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ParentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation_Description = `-- name: UpdateLocation_Description :exec
UPDATE locations SET description = $2 WHERE id = $1
`

type UpdateLocation_DescriptionParams struct {
	ID          int64       `json:"id"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateLocation_Description(ctx context.Context, arg UpdateLocation_DescriptionParams) error {
	_, err := q.db.Exec(ctx, updateLocation_Description, arg.ID, arg.Description)
	return err
}

const updateLocation_Name = `-- name: UpdateLocation_Name :exec
UPDATE locations SET name = $2 WHERE id = $1
`

type UpdateLocation_NameParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateLocation_Name(ctx context.Context, arg UpdateLocation_NameParams) error {
	_, err := q.db.Exec(ctx, updateLocation_Name, arg.ID, arg.Name)
	return err
}

const updateLocation_ParentID = `-- name: UpdateLocation_ParentID :exec
UPDATE locations SET parent_id = $2 WHERE id = $1
`

type UpdateLocation_ParentIDParams struct {
	ID       int64       `json:"id"`
	ParentID pgtype.Int8 `json:"parent_id"`
}

func (q *Queries) UpdateLocation_ParentID(ctx context.Context, arg UpdateLocation_ParentIDParams) error {
	_, err := q.db.Exec(ctx, updateLocation_ParentID, arg.ID, arg.ParentID)
	return err
}
