// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: low_stock.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearLowStockAlerts = `-- name: ClearLowStockAlerts :execrows
DELETE FROM low_stock_alerts WHERE type_id = $1
`

func (q *Queries) ClearLowStockAlerts(ctx context.Context, typeID int64) (int64, error) {
	result, err := q.db.Exec(ctx, clearLowStockAlerts, typeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLowStockAlerts = `-- name: DeleteLowStockAlerts :execrows
DELETE FROM low_stock_alerts
WHERE type_id = $1 AND group_name = ANY($2::text[])
`

type DeleteLowStockAlertsParams struct {
	TypeID     int64    `json:"type_id"`
	GroupNames []string `json:"group_names"`
}

func (q *Queries) DeleteLowStockAlerts(ctx context.Context, arg DeleteLowStockAlertsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLowStockAlerts, arg.TypeID, arg.GroupNames)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const groupItemCountsForGroups = `-- name: GroupItemCountsForGroups :many
WITH requested_groups AS (
  SELECT DISTINCT requested.group_name
  FROM unnest($2::text[]) AS requested(group_name)
)
SELECT
  requested_groups.group_name::text AS group_name,
  count(items.id) FILTER (
    WHERE items.consumption = 'not_consumed' AND approved_request.item_id IS NULL
  ) AS in_stock_count,
  count(items.id) AS total_count
FROM requested_groups
JOIN item_types ON item_types.id = $1
LEFT JOIN items
  ON items.type_id = item_types.id
 AND render_item_derived_name(items.id, item_types.derived_name_format) = requested_groups.group_name
LEFT JOIN item_requests AS approved_request
  ON approved_request.item_id = items.id
 AND approved_request.status = 'approved'
GROUP BY requested_groups.group_name
`

type GroupItemCountsForGroupsParams struct {
	TypeID     int64    `json:"type_id"`
	GroupNames []string `json:"group_names"`
}

type GroupItemCountsForGroupsRow struct {
	GroupName    string `json:"group_name"`
	InStockCount int64  `json:"in_stock_count"`
	TotalCount   int64  `json:"total_count"`
}

func (q *Queries) GroupItemCountsForGroups(ctx context.Context, arg GroupItemCountsForGroupsParams) ([]GroupItemCountsForGroupsRow, error) {
	rows, err := q.db.Query(ctx, groupItemCountsForGroups, arg.TypeID, arg.GroupNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupItemCountsForGroupsRow
	for rows.Next() {
		var i GroupItemCountsForGroupsRow
		if err := rows.Scan(&i.GroupName, &i.InStockCount, &i.TotalCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLowStockAlert = `-- name: InsertLowStockAlert :execrows
INSERT INTO low_stock_alerts (type_id, group_name)
VALUES ($1, $2)
ON CONFLICT (type_id, group_name) DO NOTHING
`

type InsertLowStockAlertParams struct {
	TypeID    int64  `json:"type_id"`
	GroupName string `json:"group_name"`
}

func (q *Queries) InsertLowStockAlert(ctx context.Context, arg InsertLowStockAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLowStockAlert, arg.TypeID, arg.GroupName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listLowStockAlerts = `-- name: ListLowStockAlerts :many
SELECT type_id, group_name, notified_at FROM low_stock_alerts
WHERE type_id = $1
`

func (q *Queries) ListLowStockAlerts(ctx context.Context, typeID int64) ([]LowStockAlert, error) {
	rows, err := q.db.Query(ctx, listLowStockAlerts, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LowStockAlert
	for rows.Next() {
		var i LowStockAlert
		if err := rows.Scan(&i.TypeID, &i.GroupName, &i.NotifiedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLowStockAlertsForGroups = `-- name: ListLowStockAlertsForGroups :many
SELECT type_id, group_name, notified_at FROM low_stock_alerts
WHERE type_id = $1 AND group_name = ANY($2::text[])
`

type ListLowStockAlertsForGroupsParams struct {
	TypeID     int64    `json:"type_id"`
	GroupNames []string `json:"group_names"`
}

func (q *Queries) ListLowStockAlertsForGroups(ctx context.Context, arg ListLowStockAlertsForGroupsParams) ([]LowStockAlert, error) {
	rows, err := q.db.Query(ctx, listLowStockAlertsForGroups, arg.TypeID, arg.GroupNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LowStockAlert
	for rows.Next() {
		var i LowStockAlert
		if err := rows.Scan(&i.TypeID, &i.GroupName, &i.NotifiedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockGroups = `-- name: ListStockGroups :many
SELECT
  item_types.id AS type_id,
  item_types.name AS type_name,
  item_types.low_stock_count,
  render_item_derived_name(items.id, item_types.derived_name_format) AS group_name,
  count(*) FILTER (
    WHERE items.consumption = 'not_consumed' AND approved_request.item_id IS NULL
  ) AS in_stock_count,
  count(*) AS total_count
FROM items
JOIN item_types ON item_types.id = items.type_id
LEFT JOIN item_requests AS approved_request
  ON approved_request.item_id = items.id
 AND approved_request.status = 'approved'
WHERE ($1::bigint IS NULL OR items.type_id = $1)
GROUP BY item_types.id, group_name
ORDER BY in_stock_count, item_types.name, group_name
`

type ListStockGroupsRow struct {
	TypeID        int64       `json:"type_id"`
	TypeName      string      `json:"type_name"`
	LowStockCount pgtype.Int4 `json:"low_stock_count"`
	GroupName     string      `json:"group_name"`
	InStockCount  int64       `json:"in_stock_count"`
	TotalCount    int64       `json:"total_count"`
}

// Stock is an aggregate, never a stored number: items holds one row per physical item and nothing
// records a quantity. What makes two of those rows the same stock is their rendered derived name, so
// that is what the count groups by.
//
// The grouping deliberately spans every item of the type whatever its state, while only items that
// are actually available count as stock. That split is the whole point. A group that has been used up
// has no available rows left, and a plain GROUP BY over in-stock items would drop it from the result
// entirely - losing precisely the group worth warning about. Counting inside a FILTER instead keeps
// the consumed rows present as evidence the group exists, and reports it at zero.
//
// Available means untouched and on the shelf: an item someone holds an approved request for is spoken
// for and cannot be handed to anyone else, so it is not stock however full it still is. The join
// mirrors the one ListItems filters by; idx_unique_approved_item_requests caps it at one row per
// item, which is what keeps it from inflating total_count.
//
// A null type_id counts the whole inventory instead of one type, which is the same question asked of
// everything at once. The type rides along in the select because a group name only identifies a
// stock line within one type, and the threshold because it is per type and there is otherwise no way
// to tell a short group from a healthy one.
//
// Deliberately unlimited. One caller wants the scarcest groups and another the largest, which are
// opposite ends of this ordering, so a LIMIT would serve the first and quietly truncate the second.
func (q *Queries) ListStockGroups(ctx context.Context, typeID pgtype.Int8) ([]ListStockGroupsRow, error) {
	rows, err := q.db.Query(ctx, listStockGroups, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStockGroupsRow
	for rows.Next() {
		var i ListStockGroupsRow
		if err := rows.Scan(
			&i.TypeID,
			&i.TypeName,
			&i.LowStockCount,
			&i.GroupName,
			&i.InStockCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumStockQuantities = `-- name: SumStockQuantities :many
SELECT
  item_types.id AS type_id,
  render_item_derived_name(items.id, item_types.derived_name_format) AS group_name,
  properties.id AS property_id,
  properties.name AS property_name,
  properties.value_type,
  trim_scale(sum(
    (item_property.property_value ->> 'amount')::numeric * COALESCE(unit_factor.factor, 1)
  ))::text AS total_amount,
  count(*) AS value_count
FROM items
JOIN item_types ON item_types.id = items.type_id
JOIN item_properties AS item_property ON item_property.item_id = items.id
JOIN properties ON properties.id = item_property.property_id AND properties.value_type IN ('mass', 'volume')
LEFT JOIN item_requests AS approved_request
  ON approved_request.item_id = items.id
 AND approved_request.status = 'approved'
LEFT JOIN ROWS FROM (
  unnest($1::text[]),
  unnest($2::text[]),
  unnest($3::bigint[])
) AS unit_factor(value_type, unit_name, factor)
  ON unit_factor.value_type = properties.value_type
 AND unit_factor.unit_name = item_property.property_value ->> 'unit'
WHERE items.consumption = 'not_consumed'
  AND approved_request.item_id IS NULL
  AND unit_factor.factor IS NOT NULL
  AND ($4::bigint IS NULL OR items.type_id = $4)
GROUP BY item_types.id, group_name, properties.id, properties.value_type
ORDER BY item_types.id, group_name, properties.id
`

type SumStockQuantitiesParams struct {
	UnitValueTypes []string    `json:"unit_value_types"`
	UnitNames      []string    `json:"unit_names"`
	UnitFactors    []int64     `json:"unit_factors"`
	TypeID         pgtype.Int8 `json:"type_id"`
}

type SumStockQuantitiesRow struct {
	TypeID       int64  `json:"type_id"`
	GroupName    string `json:"group_name"`
	PropertyID   int64  `json:"property_id"`
	PropertyName string `json:"property_name"`
	ValueType    string `json:"value_type"`
	TotalAmount  string `json:"total_amount"`
	ValueCount   int64  `json:"value_count"`
}

func (q *Queries) SumStockQuantities(ctx context.Context, arg SumStockQuantitiesParams) ([]SumStockQuantitiesRow, error) {
	rows, err := q.db.Query(ctx, sumStockQuantities,
		arg.UnitValueTypes,
		arg.UnitNames,
		arg.UnitFactors,
		arg.TypeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumStockQuantitiesRow
	for rows.Next() {
		var i SumStockQuantitiesRow
		if err := rows.Scan(
			&i.TypeID,
			&i.GroupName,
			&i.PropertyID,
			&i.PropertyName,
			&i.ValueType,
			&i.TotalAmount,
			&i.ValueCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
