// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: low_stock.sql

package repository

import (
	"context"
)

const clearLowStockAlerts = `-- name: ClearLowStockAlerts :execrows
DELETE FROM low_stock_alerts WHERE type_id = $1
`

func (q *Queries) ClearLowStockAlerts(ctx context.Context, typeID int64) (int64, error) {
	result, err := q.db.Exec(ctx, clearLowStockAlerts, typeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLowStockAlerts = `-- name: DeleteLowStockAlerts :execrows
DELETE FROM low_stock_alerts
WHERE type_id = $1 AND group_name = ANY($2::text[])
`

type DeleteLowStockAlertsParams struct {
	TypeID     int64    `json:"type_id"`
	GroupNames []string `json:"group_names"`
}

func (q *Queries) DeleteLowStockAlerts(ctx context.Context, arg DeleteLowStockAlertsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLowStockAlerts, arg.TypeID, arg.GroupNames)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const groupItemCounts = `-- name: GroupItemCounts :many
SELECT
  render_item_derived_name(items.id, item_types.derived_name_format) AS group_name,
  count(*) FILTER (
    WHERE items.consumption = 'not_consumed' AND approved_request.item_id IS NULL
  ) AS in_stock_count,
  count(*) AS total_count
FROM items
JOIN item_types ON item_types.id = items.type_id
LEFT JOIN item_requests AS approved_request
  ON approved_request.item_id = items.id
 AND approved_request.status = 'approved'
WHERE items.type_id = $1
GROUP BY group_name
ORDER BY in_stock_count, group_name
`

type GroupItemCountsRow struct {
	GroupName    string `json:"group_name"`
	InStockCount int64  `json:"in_stock_count"`
	TotalCount   int64  `json:"total_count"`
}

// Stock is an aggregate, never a stored number: items holds one row per physical item and nothing
// records a quantity. What makes two of those rows the same stock is their rendered derived name, so
// that is what the count groups by.
//
// The grouping deliberately spans every item of the type whatever its state, while only items that
// are actually available count as stock. That split is the whole point. A group that has been used up
// has no available rows left, and a plain GROUP BY over in-stock items would drop it from the result
// entirely - losing precisely the group worth warning about. Counting inside a FILTER instead keeps
// the consumed rows present as evidence the group exists, and reports it at zero.
//
// Available means untouched and on the shelf: an item someone holds an approved request for is spoken
// for and cannot be handed to anyone else, so it is not stock however full it still is. The join
// mirrors the one ListItems filters by; idx_unique_approved_item_requests caps it at one row per
// item, which is what keeps it from inflating total_count.
func (q *Queries) GroupItemCounts(ctx context.Context, typeID int64) ([]GroupItemCountsRow, error) {
	rows, err := q.db.Query(ctx, groupItemCounts, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupItemCountsRow
	for rows.Next() {
		var i GroupItemCountsRow
		if err := rows.Scan(&i.GroupName, &i.InStockCount, &i.TotalCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLowStockAlert = `-- name: InsertLowStockAlert :execrows
INSERT INTO low_stock_alerts (type_id, group_name)
VALUES ($1, $2)
ON CONFLICT (type_id, group_name) DO NOTHING
`

type InsertLowStockAlertParams struct {
	TypeID    int64  `json:"type_id"`
	GroupName string `json:"group_name"`
}

func (q *Queries) InsertLowStockAlert(ctx context.Context, arg InsertLowStockAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLowStockAlert, arg.TypeID, arg.GroupName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listLowStockAlerts = `-- name: ListLowStockAlerts :many
SELECT type_id, group_name, notified_at FROM low_stock_alerts
WHERE type_id = $1
`

func (q *Queries) ListLowStockAlerts(ctx context.Context, typeID int64) ([]LowStockAlert, error) {
	rows, err := q.db.Query(ctx, listLowStockAlerts, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LowStockAlert
	for rows.Next() {
		var i LowStockAlert
		if err := rows.Scan(&i.TypeID, &i.GroupName, &i.NotifiedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
