// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ConsumptionStatus string

const (
	ConsumptionStatusNotConsumed       ConsumptionStatus = "not_consumed"
	ConsumptionStatusPartiallyConsumed ConsumptionStatus = "partially_consumed"
	ConsumptionStatusFullyConsumed     ConsumptionStatus = "fully_consumed"
	ConsumptionStatusDamaged           ConsumptionStatus = "damaged"
)

func (e *ConsumptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConsumptionStatus(s)
	case string:
		*e = ConsumptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ConsumptionStatus: %T", src)
	}
	return nil
}

type NullConsumptionStatus struct {
	ConsumptionStatus ConsumptionStatus `json:"consumption_status"`
	Valid             bool              `json:"valid"` // Valid is true if ConsumptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConsumptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ConsumptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConsumptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConsumptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConsumptionStatus), nil
}

type NotifdescExpiryType string

const (
	NotifdescExpiryTypeExpiringSoon NotifdescExpiryType = "expiring_soon"
	NotifdescExpiryTypeExpired      NotifdescExpiryType = "expired"
)

func (e *NotifdescExpiryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotifdescExpiryType(s)
	case string:
		*e = NotifdescExpiryType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotifdescExpiryType: %T", src)
	}
	return nil
}

type NullNotifdescExpiryType struct {
	NotifdescExpiryType NotifdescExpiryType `json:"notifdesc_expiry_type"`
	Valid               bool                `json:"valid"` // Valid is true if NotifdescExpiryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotifdescExpiryType) Scan(value interface{}) error {
	if value == nil {
		ns.NotifdescExpiryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotifdescExpiryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotifdescExpiryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotifdescExpiryType), nil
}

type NotificationKind string

const (
	NotificationKindItemRequest NotificationKind = "item_request"
	NotificationKindItemExpiry  NotificationKind = "item_expiry"
)

func (e *NotificationKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationKind(s)
	case string:
		*e = NotificationKind(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationKind: %T", src)
	}
	return nil
}

type NullNotificationKind struct {
	NotificationKind NotificationKind `json:"notification_kind"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationKind) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationKind), nil
}

type PropertyVisibility string

const (
	PropertyVisibilityOverview PropertyVisibility = "overview"
	PropertyVisibilityDetails  PropertyVisibility = "details"
)

func (e *PropertyVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PropertyVisibility(s)
	case string:
		*e = PropertyVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for PropertyVisibility: %T", src)
	}
	return nil
}

type NullPropertyVisibility struct {
	PropertyVisibility PropertyVisibility `json:"property_visibility"`
	Valid              bool               `json:"valid"` // Valid is true if PropertyVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPropertyVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.PropertyVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PropertyVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPropertyVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PropertyVisibility), nil
}

type RequestStatus string

const (
	RequestStatusRequested RequestStatus = "requested"
	RequestStatusApproved  RequestStatus = "approved"
)

func (e *RequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestStatus(s)
	case string:
		*e = RequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestStatus: %T", src)
	}
	return nil
}

type NullRequestStatus struct {
	RequestStatus RequestStatus `json:"request_status"`
	Valid         bool          `json:"valid"` // Valid is true if RequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestStatus), nil
}

type UserRole string

const (
	UserRoleAdmin   UserRole = "admin"
	UserRoleManager UserRole = "manager"
	UserRoleUser    UserRole = "user"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusRequested UserStatus = "requested"
	UserStatusActive    UserStatus = "active"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type Item struct {
	ID          int64              `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Consumption ConsumptionStatus  `json:"consumption"`
	TypeID      int64              `json:"type_id"`
}

type ItemProperty struct {
	ItemID        int64           `json:"item_id"`
	PropertyID    int64           `json:"property_id"`
	PropertyValue json.RawMessage `json:"property_value"`
}

type ItemRequest struct {
	UserID    int64              `json:"user_id"`
	ItemID    int64              `json:"item_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Status    RequestStatus      `json:"status"`
	Reason    string             `json:"reason"`
}

type ItemType struct {
	ID                int64       `json:"id"`
	Name              string      `json:"name"`
	Description       pgtype.Text `json:"description"`
	DerivedNameFormat pgtype.Text `json:"derived_name_format"`
}

type ItemTypeProperty struct {
	TypeID       int64              `json:"type_id"`
	PropertyID   int64              `json:"property_id"`
	DefaultValue *json.RawMessage   `json:"default_value"`
	Visibility   PropertyVisibility `json:"visibility"`
	Position     int32              `json:"position"`
}

type NotifdescItemExpiry struct {
	NotificationID int64                `json:"notification_id"`
	Kind           NullNotificationKind `json:"kind"`
	ItemID         int64                `json:"item_id"`
	ExpiryType     NotifdescExpiryType  `json:"expiry_type"`
}

type NotifdescItemRequest struct {
	NotificationID int64                `json:"notification_id"`
	Kind           NullNotificationKind `json:"kind"`
	UserID         int64                `json:"user_id"`
	ItemID         int64                `json:"item_id"`
}

type Notification struct {
	ID          int64              `json:"id"`
	RecipientID int64              `json:"recipient_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Kind        NotificationKind   `json:"kind"`
	Read        bool               `json:"read"`
}

type Property struct {
	ID           int64            `json:"id"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	ValueType    string           `json:"value_type"`
	DefaultValue *json.RawMessage `json:"default_value"`
}

type User struct {
	ID           int64      `json:"id"`
	Email        string     `json:"email"`
	PasswordHash string     `json:"password_hash"`
	FullName     string     `json:"full_name"`
	Role         UserRole   `json:"role"`
	Status       UserStatus `json:"status"`
}
