// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package repository

import (
	"context"
)

const countNotifications = `-- name: CountNotifications :one
SELECT count(*) FROM notifications
WHERE recipient_id = $1
`

func (q *Queries) CountNotifications(ctx context.Context, recipientID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications
WHERE recipient_id = $1 AND read = true
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, recipientID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotificationDescriptors_ItemExpiry = `-- name: CreateNotificationDescriptors_ItemExpiry :many
INSERT INTO notifdesc_item_expiry (notification_id, item_id, expiry_type) 
VALUES (unnest($3::bigint[]), $1, $2)
RETURNING notification_id, kind, item_id, expiry_type
`

type CreateNotificationDescriptors_ItemExpiryParams struct {
	ItemID          int64               `json:"item_id"`
	ExpiryType      NotifdescExpiryType `json:"expiry_type"`
	NotificationIds []int64             `json:"notification_ids"`
}

func (q *Queries) CreateNotificationDescriptors_ItemExpiry(ctx context.Context, arg CreateNotificationDescriptors_ItemExpiryParams) ([]NotifdescItemExpiry, error) {
	rows, err := q.db.Query(ctx, createNotificationDescriptors_ItemExpiry, arg.ItemID, arg.ExpiryType, arg.NotificationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotifdescItemExpiry
	for rows.Next() {
		var i NotifdescItemExpiry
		if err := rows.Scan(
			&i.NotificationID,
			&i.Kind,
			&i.ItemID,
			&i.ExpiryType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNotificationDescriptors_ItemRequest = `-- name: CreateNotificationDescriptors_ItemRequest :many
INSERT INTO notifdesc_item_request (notification_id, user_id, item_id) 
VALUES (unnest($3::bigint[]), $1, $2)
RETURNING notification_id, kind, user_id, item_id
`

type CreateNotificationDescriptors_ItemRequestParams struct {
	UserID          int64   `json:"user_id"`
	ItemID          int64   `json:"item_id"`
	NotificationIds []int64 `json:"notification_ids"`
}

func (q *Queries) CreateNotificationDescriptors_ItemRequest(ctx context.Context, arg CreateNotificationDescriptors_ItemRequestParams) ([]NotifdescItemRequest, error) {
	rows, err := q.db.Query(ctx, createNotificationDescriptors_ItemRequest, arg.UserID, arg.ItemID, arg.NotificationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotifdescItemRequest
	for rows.Next() {
		var i NotifdescItemRequest
		if err := rows.Scan(
			&i.NotificationID,
			&i.Kind,
			&i.UserID,
			&i.ItemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNotifications = `-- name: CreateNotifications :many
INSERT INTO notifications (recipient_id, kind) 
VALUES (unnest($2::bigint[]), $1)
RETURNING id, recipient_id, created_at, kind, read
`

type CreateNotificationsParams struct {
	Kind         NotificationKind `json:"kind"`
	RecipientIds []int64          `json:"recipient_ids"`
}

func (q *Queries) CreateNotifications(ctx context.Context, arg CreateNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, createNotifications, arg.Kind, arg.RecipientIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.CreatedAt,
			&i.Kind,
			&i.Read,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteNotification = `-- name: DeleteNotification :execrows
DELETE FROM notifications WHERE id = $1 AND recipient_id = $2
`

type DeleteNotificationParams struct {
	ID          int64 `json:"id"`
	RecipientID int64 `json:"recipient_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.RecipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT 
    notif.id, notif.recipient_id, notif.created_at, notif.kind, notif.read, 
    notifdesc_item_request.notification_id, notifdesc_item_request.kind, notifdesc_item_request.user_id, notifdesc_item_request.item_id,
    notifdesc_item_expiry.notification_id, notifdesc_item_expiry.kind, notifdesc_item_expiry.item_id, notifdesc_item_expiry.expiry_type
FROM notifications AS notif
LEFT JOIN notifdesc_item_request 
    ON notif.id = notifdesc_item_request.notification_id
LEFT JOIN notifdesc_item_expiry 
    ON notif.id = notifdesc_item_expiry.notification_id
WHERE recipient_id = $1
ORDER BY notif.created_at
LIMIT $3 OFFSET $2
`

type ListNotificationsParams struct {
	RecipientID int64 `json:"recipient_id"`
	PageOffset  int32 `json:"page_offset"`
	PageLimit   int32 `json:"page_limit"`
}

type ListNotificationsRow struct {
	Notification         Notification         `json:"notification"`
	NotifdescItemRequest NotifdescItemRequest `json:"notifdesc_item_request"`
	NotifdescItemExpiry  NotifdescItemExpiry  `json:"notifdesc_item_expiry"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.RecipientID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsRow
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.Notification.ID,
			&i.Notification.RecipientID,
			&i.Notification.CreatedAt,
			&i.Notification.Kind,
			&i.Notification.Read,
			&i.NotifdescItemRequest.NotificationID,
			&i.NotifdescItemRequest.Kind,
			&i.NotifdescItemRequest.UserID,
			&i.NotifdescItemRequest.ItemID,
			&i.NotifdescItemExpiry.NotificationID,
			&i.NotifdescItemExpiry.Kind,
			&i.NotifdescItemExpiry.ItemID,
			&i.NotifdescItemExpiry.ExpiryType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readNotifications = `-- name: ReadNotifications :execrows
UPDATE notifications
SET read = true
WHERE read = false AND recipient_id = $1
`

func (q *Queries) ReadNotifications(ctx context.Context, recipientID int64) (int64, error) {
	result, err := q.db.Exec(ctx, readNotifications, recipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
