// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: properties.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProperties = `-- name: CountProperties :one
SELECT count(*) FROM properties
`

func (q *Queries) CountProperties(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProperties)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProperty = `-- name: CreateProperty :one
INSERT INTO properties (name, description, value_type, default_value) VALUES ($1, $2, $3, $4) RETURNING id, name, description, value_type, default_value
`

type CreatePropertyParams struct {
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	ValueType    string      `json:"value_type"`
	DefaultValue *string     `json:"default_value"`
}

func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error) {
	row := q.db.QueryRow(ctx, createProperty,
		arg.Name,
		arg.Description,
		arg.ValueType,
		arg.DefaultValue,
	)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ValueType,
		&i.DefaultValue,
	)
	return i, err
}

const deleteProperty = `-- name: DeleteProperty :execrows
DELETE FROM properties WHERE id = $1
`

func (q *Queries) DeleteProperty(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProperty, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllProperties = `-- name: GetAllProperties :many
SELECT id, name, description, value_type, default_value FROM properties
`

func (q *Queries) GetAllProperties(ctx context.Context) ([]Property, error) {
	rows, err := q.db.Query(ctx, getAllProperties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Property
	for rows.Next() {
		var i Property
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ValueType,
			&i.DefaultValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPropertyByID = `-- name: GetPropertyByID :one
SELECT id, name, description, value_type, default_value FROM properties
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPropertyByID(ctx context.Context, id int64) (Property, error) {
	row := q.db.QueryRow(ctx, getPropertyByID, id)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ValueType,
		&i.DefaultValue,
	)
	return i, err
}

const listProperties = `-- name: ListProperties :many
SELECT id, name, description, value_type, default_value FROM properties
ORDER BY id
LIMIT $2 OFFSET $1
`

type ListPropertiesParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

func (q *Queries) ListProperties(ctx context.Context, arg ListPropertiesParams) ([]Property, error) {
	rows, err := q.db.Query(ctx, listProperties, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Property
	for rows.Next() {
		var i Property
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ValueType,
			&i.DefaultValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPropertyOptions = `-- name: ListPropertyOptions :many
SELECT id, name, value_type, default_value FROM properties
ORDER BY name
`

type ListPropertyOptionsRow struct {
	ID           int64   `json:"id"`
	Name         string  `json:"name"`
	ValueType    string  `json:"value_type"`
	DefaultValue *string `json:"default_value"`
}

func (q *Queries) ListPropertyOptions(ctx context.Context) ([]ListPropertyOptionsRow, error) {
	rows, err := q.db.Query(ctx, listPropertyOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPropertyOptionsRow
	for rows.Next() {
		var i ListPropertyOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ValueType,
			&i.DefaultValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProperty_DefaultValue = `-- name: UpdateProperty_DefaultValue :exec
UPDATE properties SET default_value = $2 WHERE id = $1
`

type UpdateProperty_DefaultValueParams struct {
	ID           int64   `json:"id"`
	DefaultValue *string `json:"default_value"`
}

func (q *Queries) UpdateProperty_DefaultValue(ctx context.Context, arg UpdateProperty_DefaultValueParams) error {
	_, err := q.db.Exec(ctx, updateProperty_DefaultValue, arg.ID, arg.DefaultValue)
	return err
}

const updateProperty_Description = `-- name: UpdateProperty_Description :exec
UPDATE properties SET description = $2 WHERE id = $1
`

type UpdateProperty_DescriptionParams struct {
	ID          int64       `json:"id"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateProperty_Description(ctx context.Context, arg UpdateProperty_DescriptionParams) error {
	_, err := q.db.Exec(ctx, updateProperty_Description, arg.ID, arg.Description)
	return err
}

const updateProperty_Name = `-- name: UpdateProperty_Name :exec
UPDATE properties SET name = $2 WHERE id = $1
`

type UpdateProperty_NameParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateProperty_Name(ctx context.Context, arg UpdateProperty_NameParams) error {
	_, err := q.db.Exec(ctx, updateProperty_Name, arg.ID, arg.Name)
	return err
}
