// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddItemProperty(ctx context.Context, arg AddItemPropertyParams) (ItemProperty, error)
	AddItemPropertyBulk(ctx context.Context, arg AddItemPropertyBulkParams) ([]ItemProperty, error)
	AddItemTypeProperty(ctx context.Context, arg AddItemTypePropertyParams) (ItemTypeProperty, error)
	ApproveItemRequest(ctx context.Context, arg ApproveItemRequestParams) (ItemRequest, error)
	CheckItemsForRequests(ctx context.Context, itemIds []int64) ([]ItemRequest, error)
	ClearLowStockAlerts(ctx context.Context, typeID int64) (int64, error)
	CountAuditLog(ctx context.Context, arg CountAuditLogParams) (int64, error)
	// An item records the state it is in, never when it got there, so the log is the only thing that
	// can date a consumption.
	//
	// Consumption is a status rather than an event, and correcting one later writes a second entry.
	// Requiring the change to start at not_consumed counts each item the once it left the shelf. The
	// diff is stored JSON-encoded, which is why ->> hands back a bare enum name, and a consumption
	// entry only ever holds the one change.
	//
	// The created_at bound repeats what the join already does, to keep the index in play.
	//
	// Narrowing by type has to reach the item, and target_id has no foreign key to reach it with: an
	// item consumed and since deleted counts when no type is asked for, and drops out when one is.
	CountConsumptionByMonth(ctx context.Context, arg CountConsumptionByMonthParams) ([]CountConsumptionByMonthRow, error)
	CountExpiredBacklog(ctx context.Context, typeID pgtype.Int8) (int64, error)
	// An expiry is stored as a date string, and nothing stops a bad one getting in. The CASE is what
	// guards the cast - putting the check in the WHERE would not, since Postgres is free to evaluate
	// the two in either order.
	//
	// The months are generated rather than read off the rows, so a period where nothing expires still
	// gets a bar. Generating them in the database keeps one clock in charge of which month is current.
	CountExpiringByMonth(ctx context.Context, arg CountExpiringByMonthParams) ([]CountExpiringByMonthRow, error)
	CountItemRequests(ctx context.Context, arg CountItemRequestsParams) (int64, error)
	CountItemTypes(ctx context.Context, search string) (int64, error)
	CountItems(ctx context.Context, arg CountItemsParams) (int64, error)
	CountLocations(ctx context.Context, search string) (int64, error)
	CountNotifications(ctx context.Context, recipientID int64) (int64, error)
	CountProperties(ctx context.Context, search string) (int64, error)
	CountUnreadNotifications(ctx context.Context, recipientID int64) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateItemRequest(ctx context.Context, arg CreateItemRequestParams) (ItemRequest, error)
	CreateItemType(ctx context.Context, arg CreateItemTypeParams) (ItemType, error)
	CreateItems(ctx context.Context, arg CreateItemsParams) ([]Item, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateNotificationDescriptors_ItemExpiry(ctx context.Context, arg CreateNotificationDescriptors_ItemExpiryParams) ([]NotifdescItemExpiry, error)
	CreateNotificationDescriptors_ItemRequest(ctx context.Context, arg CreateNotificationDescriptors_ItemRequestParams) ([]NotifdescItemRequest, error)
	CreateNotificationDescriptors_LowStock(ctx context.Context, arg CreateNotificationDescriptors_LowStockParams) ([]NotifdescLowStock, error)
	CreateNotifications(ctx context.Context, arg CreateNotificationsParams) ([]Notification, error)
	CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteItem(ctx context.Context, id int64) (int64, error)
	DeleteItemRequest(ctx context.Context, arg DeleteItemRequestParams) (int64, error)
	DeleteItemType(ctx context.Context, id int64) (int64, error)
	DeleteLocation(ctx context.Context, id int64) (int64, error)
	DeleteLowStockAlerts(ctx context.Context, arg DeleteLowStockAlertsParams) (int64, error)
	DeleteNonApprovedItemRequests(ctx context.Context, itemID int64) (int64, error)
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) (int64, error)
	DeleteProperty(ctx context.Context, id int64) (int64, error)
	DeleteUser(ctx context.Context, id int64) (int64, error)
	GetAllItemTypes(ctx context.Context) ([]ItemType, error)
	// One entry on its own, for the page that shows a single change in full. The row already carries its
	// diff and context, so nothing else has to be resolved to render it.
	GetAuditLogEntry(ctx context.Context, id int64) (AuditLog, error)
	GetItemByID(ctx context.Context, id int64) (Item, error)
	GetItemProperties(ctx context.Context, itemIds []int64) ([]GetItemPropertiesRow, error)
	GetItemRequest(ctx context.Context, arg GetItemRequestParams) (ItemRequest, error)
	GetItemTypeByID(ctx context.Context, id int64) (ItemType, error)
	GetItemTypeProperties(ctx context.Context, typeIds []int64) ([]ItemTypeProperty, error)
	GetItemTypesByItemIDs(ctx context.Context, itemIds []int64) ([]GetItemTypesByItemIDsRow, error)
	GetItemsDerivedNames(ctx context.Context, itemIds []int64) ([]GetItemsDerivedNamesRow, error)
	GetItemsRequestStatuses(ctx context.Context, arg GetItemsRequestStatusesParams) ([]GetItemsRequestStatusesRow, error)
	GetLocationByID(ctx context.Context, id int64) (Location, error)
	GetLocationChildren(ctx context.Context, parentID int64) ([]GetLocationChildrenRow, error)
	GetLocationsAncestors(ctx context.Context, id []int64) ([]GetLocationsAncestorsRow, error)
	// Every property, or just the ones named. The filter is optional so one query serves both the full
	// catalogue and the audit path, which resolves a handful of names at once for an entry spanning
	// several properties - a reorder, or the initial list of a new item type.
	GetProperties(ctx context.Context, propertyIds []int64) ([]Property, error)
	GetPropertyByID(ctx context.Context, id int64) (Property, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUsersByRoles(ctx context.Context, arg GetUsersByRolesParams) ([]User, error)
	GroupItemCountsForGroups(ctx context.Context, arg GroupItemCountsForGroupsParams) ([]GroupItemCountsForGroupsRow, error)
	HasApprovedItemRequest(ctx context.Context, itemID int64) (bool, error)
	Healthcheck(ctx context.Context) (int32, error)
	InsertLowStockAlert(ctx context.Context, arg InsertLowStockAlertParams) (int64, error)
	// Newest first. The id tiebreaker keeps pagination stable: a bulk add writes a whole batch of rows
	// under one created_at.
	ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error)
	// Everyone who has ever made a recorded change, for the actor filter. Mirrors ListItemRequestUsers.
	//
	// Driven from users rather than from audit_log: DISTINCT ON cannot skip-scan in Postgres, so
	// reading it the other way round sorts the whole log - a table that only ever grows and is never
	// pruned - to produce a handful of rows. EXISTS turns that into one index lookup per user against
	// idx_audit_log_actor, so the cost tracks the number of users instead of the size of the history.
	//
	// Deleted users drop out either way: their actor_id is nulled, so there is no id left to filter by.
	// Their entries stay in the log and still show the name they acted under - they just cannot be
	// singled out by this filter any more.
	ListAuditLogActors(ctx context.Context) ([]ListAuditLogActorsRow, error)
	// What a manager has to act on rather than only count: everything already past its date, plus what
	// falls inside the warning window its type sets. A type without a window warns about nothing, but an
	// item that is already expired is expired either way, which is why the two are separate conditions.
	//
	// days_remaining comes back from here rather than being worked out from the date by the caller, so
	// the sign that decides expired from merely close is settled against one clock.
	//
	// The list is capped, so every row carries how many there were before the cap. Counting over the
	// window rather than in a second query is what stops the total from ever disagreeing with the
	// condition above: there is only one copy of it. A cap that hid how much it was hiding would report
	// the ceiling as though it were the answer.
	ListExpiringItems(ctx context.Context, arg ListExpiringItemsParams) ([]ListExpiringItemsRow, error)
	ListItemPreparationRequests(ctx context.Context, arg ListItemPreparationRequestsParams) ([]ListItemPreparationRequestsRow, error)
	ListItemRequestUsers(ctx context.Context) ([]ListItemRequestUsersRow, error)
	ListItemRequests(ctx context.Context, arg ListItemRequestsParams) ([]ListItemRequestsRow, error)
	ListItemTypeFilterableProperties(ctx context.Context, typeID int64) ([]ListItemTypeFilterablePropertiesRow, error)
	ListItemTypeOptions(ctx context.Context) ([]ListItemTypeOptionsRow, error)
	ListItemTypePropertyValues(ctx context.Context, arg ListItemTypePropertyValuesParams) ([]json.RawMessage, error)
	ListItemTypes(ctx context.Context, arg ListItemTypesParams) ([]ItemType, error)
	// Sorting by a property has to reach into the JSONB value, whose shape depends on the property's
	// value type, so the sort key is built as two columns - one numeric, one text - of which at most one
	// is ever non-null. Mass and volume are compared in their dimension's base unit, with the unit
	// factors arriving as three parallel arrays exactly like SumItemProperties takes them, so
	// dto.MassUnitFactors / dto.VolumeUnitFactors stay their only definition. An amount whose unit has no
	// factor gets a null key on purpose: the item sorts last instead of being read as base units.
	// With no sort property both keys are null for every row, which makes the four sort_key terms of the
	// ORDER BY a no-op and leaves creation order as the only one. Items missing the sorted property keep
	// null keys too, and so land last whichever direction is asked for.
	ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error)
	ListLocationOptions(ctx context.Context) ([]ListLocationOptionsRow, error)
	ListLowStockAlerts(ctx context.Context, typeID int64) ([]LowStockAlert, error)
	ListLowStockAlertsForGroups(ctx context.Context, arg ListLowStockAlertsForGroupsParams) ([]LowStockAlert, error)
	ListMostConsumedGroups(ctx context.Context, arg ListMostConsumedGroupsParams) ([]ListMostConsumedGroupsRow, error)
	// Unread first, then newest first. The id tiebreaker keeps pagination stable: notifications are
	// bulk-inserted, so a whole batch shares one created_at.
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error)
	ListProperties(ctx context.Context, arg ListPropertiesParams) ([]Property, error)
	ListPropertyOptions(ctx context.Context) ([]ListPropertyOptionsRow, error)
	// Stock is an aggregate, never a stored number: items holds one row per physical item and nothing
	// records a quantity. What makes two of those rows the same stock is their rendered derived name, so
	// that is what the count groups by.
	//
	// The grouping deliberately spans every item of the type whatever its state, while only items that
	// are actually available count as stock. That split is the whole point. A group that has been used up
	// has no available rows left, and a plain GROUP BY over in-stock items would drop it from the result
	// entirely - losing precisely the group worth warning about. Counting inside a FILTER instead keeps
	// the consumed rows present as evidence the group exists, and reports it at zero.
	//
	// Available means untouched and on the shelf: an item someone holds an approved request for is spoken
	// for and cannot be handed to anyone else, so it is not stock however full it still is. The join
	// mirrors the one ListItems filters by; idx_unique_approved_item_requests caps it at one row per
	// item, which is what keeps it from inflating total_count.
	//
	// A null type_id counts the whole inventory instead of one type, which is the same question asked of
	// everything at once. The type rides along in the select because a group name only identifies a
	// stock line within one type, and the threshold because it is per type and there is otherwise no way
	// to tell a short group from a healthy one.
	//
	// Deliberately unlimited. One caller wants the scarcest groups and another the largest, which are
	// opposite ends of this ordering, so a LIMIT would serve the first and quietly truncate the second.
	//
	ListStockGroups(ctx context.Context, typeID pgtype.Int8) ([]ListStockGroupsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LockItemForRequest(ctx context.Context, id int64) (int64, error)
	LockItemType(ctx context.Context, id int64) (ItemType, error)
	OffsetItemTypePropertyPositions(ctx context.Context, typeID int64) error
	ReadNotifications(ctx context.Context, recipientID int64) (int64, error)
	RemoveItemProperty(ctx context.Context, arg RemoveItemPropertyParams) (int64, error)
	RemoveItemTypeProperty(ctx context.Context, arg RemoveItemTypePropertyParams) (int64, error)
	SetItemTypePropertyPositions(ctx context.Context, arg SetItemTypePropertyPositionsParams) (int64, error)
	SumConsumptionQuantityByMonth(ctx context.Context, arg SumConsumptionQuantityByMonthParams) ([]SumConsumptionQuantityByMonthRow, error)
	// Sums every structured property (price, mass, volume) over the same set of items CountItems
	// counts, so the WHERE block below has to stay identical to it. Mass and volume are summed in
	// their dimension's base unit: the unit factors arrive as three parallel arrays instead of being
	// hardcoded here, so dto.MassUnitFactors / dto.VolumeUnitFactors stay the only definition of them.
	// Values whose unit has no factor are dropped rather than counted as base units.
	SumItemProperties(ctx context.Context, arg SumItemPropertiesParams) ([]SumItemPropertiesRow, error)
	SumStockQuantities(ctx context.Context, arg SumStockQuantitiesParams) ([]SumStockQuantitiesRow, error)
	UpdateItemProperty(ctx context.Context, arg UpdateItemPropertyParams) (ItemProperty, error)
	UpdateItemTypeProperty_DefaultValue(ctx context.Context, arg UpdateItemTypeProperty_DefaultValueParams) (ItemTypeProperty, error)
	UpdateItemTypeProperty_Visibility(ctx context.Context, arg UpdateItemTypeProperty_VisibilityParams) (ItemTypeProperty, error)
	UpdateItemType_DerivedNameFormat(ctx context.Context, arg UpdateItemType_DerivedNameFormatParams) (ItemType, error)
	UpdateItemType_Description(ctx context.Context, arg UpdateItemType_DescriptionParams) (ItemType, error)
	UpdateItemType_ExpiringSoonDays(ctx context.Context, arg UpdateItemType_ExpiringSoonDaysParams) (ItemType, error)
	UpdateItemType_LowStockCount(ctx context.Context, arg UpdateItemType_LowStockCountParams) (ItemType, error)
	UpdateItemType_Name(ctx context.Context, arg UpdateItemType_NameParams) (ItemType, error)
	UpdateItem_Consumption(ctx context.Context, arg UpdateItem_ConsumptionParams) (Item, error)
	UpdateItem_Location(ctx context.Context, arg UpdateItem_LocationParams) (Item, error)
	UpdateItem_Type(ctx context.Context, arg UpdateItem_TypeParams) (Item, error)
	UpdateLocation_Description(ctx context.Context, arg UpdateLocation_DescriptionParams) error
	UpdateLocation_Name(ctx context.Context, arg UpdateLocation_NameParams) error
	UpdateLocation_ParentID(ctx context.Context, arg UpdateLocation_ParentIDParams) error
	UpdateProperty_DefaultValue(ctx context.Context, arg UpdateProperty_DefaultValueParams) error
	UpdateProperty_Description(ctx context.Context, arg UpdateProperty_DescriptionParams) error
	UpdateProperty_Name(ctx context.Context, arg UpdateProperty_NameParams) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
	UpdateUserFullName(ctx context.Context, arg UpdateUserFullNameParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
	// One action against several targets in a single statement, the way CreateNotifications inserts one
	// row per recipient. Used by CreateItem, which makes up to 100 items in a call and gives each its
	// own entry so that its timeline starts with its creation.
	WriteAuditEntries(ctx context.Context, arg WriteAuditEntriesParams) error
	// The actor's display name is snapshotted here rather than looked up first, so recording a change
	// costs no extra round trip. An empty actor_name means there was no user behind the change at all -
	// the seeder, or a future background job - which the client words however it likes. That is distinct
	// from a null actor_id with a name, which is a user who has since been deleted.
	WriteAuditEntry(ctx context.Context, arg WriteAuditEntryParams) error
}

var _ Querier = (*Queries)(nil)
