// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
	"encoding/json"
)

type Querier interface {
	AddItemProperty(ctx context.Context, arg AddItemPropertyParams) (ItemProperty, error)
	AddItemPropertyBulk(ctx context.Context, arg AddItemPropertyBulkParams) ([]ItemProperty, error)
	AddItemTypeProperty(ctx context.Context, arg AddItemTypePropertyParams) (ItemTypeProperty, error)
	ApproveItemRequest(ctx context.Context, arg ApproveItemRequestParams) (ItemRequest, error)
	CheckItemsForRequests(ctx context.Context, itemIds []int64) ([]ItemRequest, error)
	CountItemRequests(ctx context.Context, arg CountItemRequestsParams) (int64, error)
	CountItemTypes(ctx context.Context, search string) (int64, error)
	CountItems(ctx context.Context, arg CountItemsParams) (int64, error)
	CountProperties(ctx context.Context, search string) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateItemRequest(ctx context.Context, arg CreateItemRequestParams) (ItemRequest, error)
	CreateItemType(ctx context.Context, arg CreateItemTypeParams) (ItemType, error)
	CreateItems(ctx context.Context, arg CreateItemsParams) ([]Item, error)
	CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteItem(ctx context.Context, id int64) (int64, error)
	DeleteItemRequest(ctx context.Context, arg DeleteItemRequestParams) (int64, error)
	DeleteItemType(ctx context.Context, id int64) (int64, error)
	DeleteNonApprovedItemRequests(ctx context.Context, itemID int64) (int64, error)
	DeleteProperty(ctx context.Context, id int64) (int64, error)
	DeleteUser(ctx context.Context, id int64) (int64, error)
	GetAllItemTypes(ctx context.Context) ([]ItemType, error)
	GetAllProperties(ctx context.Context) ([]Property, error)
	GetItemByID(ctx context.Context, id int64) (Item, error)
	GetItemProperties(ctx context.Context, itemIds []int64) ([]GetItemPropertiesRow, error)
	GetItemRequest(ctx context.Context, arg GetItemRequestParams) (ItemRequest, error)
	GetItemTypeByID(ctx context.Context, id int64) (ItemType, error)
	GetItemTypeProperties(ctx context.Context, typeIds []int64) ([]ItemTypeProperty, error)
	GetItemsDerivedNames(ctx context.Context, itemIds []int64) ([]GetItemsDerivedNamesRow, error)
	GetPropertyByID(ctx context.Context, id int64) (Property, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserItemRequests(ctx context.Context, arg GetUserItemRequestsParams) ([]ItemRequest, error)
	HasApprovedItemRequest(ctx context.Context, itemID int64) (bool, error)
	Healthcheck(ctx context.Context) (int32, error)
	ListItemRequests(ctx context.Context, arg ListItemRequestsParams) ([]ListItemRequestsRow, error)
	ListItemRequestUsers(ctx context.Context) ([]ListItemRequestUsersRow, error)
	ListItemPreparationRequests(ctx context.Context, userID int64) ([]ListItemPreparationRequestsRow, error)
	ListItemTypeFilterableProperties(ctx context.Context, typeID int64) ([]ListItemTypeFilterablePropertiesRow, error)
	ListItemTypeOptions(ctx context.Context) ([]ListItemTypeOptionsRow, error)
	ListItemTypePropertyValues(ctx context.Context, arg ListItemTypePropertyValuesParams) ([]json.RawMessage, error)
	ListItemTypes(ctx context.Context, arg ListItemTypesParams) ([]ItemType, error)
	ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error)
	ListProperties(ctx context.Context, arg ListPropertiesParams) ([]Property, error)
	ListPropertyOptions(ctx context.Context) ([]ListPropertyOptionsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LockItemForRequest(ctx context.Context, id int64) (int64, error)
	RemoveItemProperty(ctx context.Context, arg RemoveItemPropertyParams) (int64, error)
	RemoveItemTypeProperty(ctx context.Context, arg RemoveItemTypePropertyParams) (int64, error)
	UpdateItemProperty(ctx context.Context, arg UpdateItemPropertyParams) (ItemProperty, error)
	UpdateItemTypeProperty_DefaultValue(ctx context.Context, arg UpdateItemTypeProperty_DefaultValueParams) (ItemTypeProperty, error)
	UpdateItemTypeProperty_Visibility(ctx context.Context, arg UpdateItemTypeProperty_VisibilityParams) (ItemTypeProperty, error)
	UpdateItemType_DerivedNameFormat(ctx context.Context, arg UpdateItemType_DerivedNameFormatParams) (ItemType, error)
	UpdateItemType_Description(ctx context.Context, arg UpdateItemType_DescriptionParams) (ItemType, error)
	UpdateItemType_Name(ctx context.Context, arg UpdateItemType_NameParams) (ItemType, error)
	UpdateItem_Consumption(ctx context.Context, arg UpdateItem_ConsumptionParams) (Item, error)
	UpdateItem_Type(ctx context.Context, arg UpdateItem_TypeParams) (Item, error)
	UpdateProperty_DefaultValue(ctx context.Context, arg UpdateProperty_DefaultValueParams) error
	UpdateProperty_Description(ctx context.Context, arg UpdateProperty_DescriptionParams) error
	UpdateProperty_Name(ctx context.Context, arg UpdateProperty_NameParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
}

var _ Querier = (*Queries)(nil)
